from pydantic import BaseModel, Field
from typing import List, Optional


class CitationError(Exception):
    """Raised when a draft cites non-existent chunk_ids."""
    pass


class HallucinationError(Exception):
    """Raised when a draft contains unsupported facts not in uncertainties."""
    pass


class TextChunk(BaseModel):
    """A chunk of text extracted from a document with metadata."""
    chunk_id: str
    text: str
    source_doc: str
    page_num: int
    confidence_score: float = Field(ge=0.0, le=1.0)


class ExtractedEntity(BaseModel):
    """A structured entity extracted from text (date, amount, party, case number)."""
    type: str  # "date", "amount", "party", "case_number"
    value: str
    source_chunk_id: str


class ProcessedDocument(BaseModel):
    """Output of the document processing stage."""
    source_path: str
    raw_text: str
    chunks: List[TextChunk]
    entities: List[ExtractedEntity]


class RetrievedEvidence(BaseModel):
    """A piece of evidence returned by the retrieval layer."""
    chunk_id: str
    text: str
    source_doc: str
    page_num: int
    score: float


class Party(BaseModel):
    """A party mentioned in a legal document."""
    name: str
    role: Optional[str] = None  # e.g., "plaintiff", "defendant"


class Fact(BaseModel):
    """A factual statement with supporting evidence citations."""
    statement: str
    supporting_evidence: List[str]  # chunk_ids


class DateEvent(BaseModel):
    """A date and the event associated with it."""
    date: str
    event: str


class Claim(BaseModel):
    """A claim or allegation with supporting evidence."""
    description: str
    supporting_evidence: List[str]


class CaseFactSummary(BaseModel):
    """The structured draft output generated by the LLM."""
    parties: List[Party]
    key_facts: List[Fact]
    dates: List[DateEvent]
    claims: List[Claim]
    uncertainties: List[str]
