from pydantic import BaseModel, Field
from typing import List, Optional


class CitationError(Exception):
    """Raised when a draft cites non-existent chunk_ids."""
    pass


class HallucinationError(Exception):
    """Raised when a draft contains unsupported facts not in uncertainties."""
    pass


class TextChunk(BaseModel):
    """A chunk of text extracted from a document with metadata."""
    chunk_id: str
    text: str
    source_doc: str
    page_num: int
    confidence_score: float = Field(ge=0.0, le=1.0)


class ExtractedEntity(BaseModel):
    """A structured entity extracted from text (date, amount, party, case number)."""
    type: str  # "date", "amount", "party", "case_number"
    value: str
    source_chunk_id: str
    start: int = 0  # character offset in raw_text
    end: int = 0    # character offset in raw_text


class ProcessedDocument(BaseModel):
    """Output of the document processing stage."""
    source_path: str
    raw_text: str
    chunks: List[TextChunk]
    entities: List[ExtractedEntity]


class RetrievedEvidence(BaseModel):
    """A piece of evidence returned by the retrieval layer."""
    chunk_id: str
    text: str
    source_doc: str
    page_num: int
    score: float


class Party(BaseModel):
    """A party mentioned in a legal document."""
    name: str
    role: Optional[str] = None  # e.g., "plaintiff", "defendant"


class Fact(BaseModel):
    """A factual statement with supporting evidence citations."""
    statement: str
    supporting_evidence: List[str]  # chunk_ids


class DateEvent(BaseModel):
    """A date and the event associated with it."""
    date: str
    event: str


class Claim(BaseModel):
    """A claim or allegation with supporting evidence."""
    description: str
    supporting_evidence: List[str]


class FinancialItem(BaseModel):
    """A monetary amount with description and evidence."""
    amount: str
    description: str
    supporting_evidence: List[str]


class CaseFactSummary(BaseModel):
    """The structured draft output generated by the LLM."""
    document_summary: str = ""
    parties: List[Party]
    key_facts: List[Fact]
    dates: List[DateEvent]
    claims: List[Claim]
    uncertainties: List[str]
    financial_summary: List[FinancialItem] = []

    def to_html(self) -> str:
        """Render a readable HTML summary from the structured data."""
        parts = ['<div class="case-summary">']

        # Title
        parts.append('<h2>Case Fact Summary</h2>')

        # Document Summary
        if self.document_summary:
            parts.append('<section class="summary-section"><h3>Document Overview</h3>')
            parts.append(f'<p style="color:#444;font-size:15px;line-height:1.6;margin:0;">{self.document_summary}</p>')
            parts.append('</section>')

        # Parties
        if self.parties:
            parts.append('<section class="summary-section"><h3>Parties</h3><div class="party-list">')
            for p in self.parties:
                role = f'<span class="party-role">{p.role}</span>' if p.role else ''
                parts.append(f'<div class="party-badge">{p.name}{role}</div>')
            parts.append('</div></section>')

        # Dates
        if self.dates:
            parts.append('<section class="summary-section"><h3>Key Dates</h3><ul class="date-list">')
            for d in self.dates:
                parts.append(f'<li><strong>{d.date}</strong> — {d.event}</li>')
            parts.append('</ul></section>')

        # Key Facts
        if self.key_facts:
            parts.append('<section class="summary-section"><h3>Key Facts</h3><ol class="fact-list">')
            for f in self.key_facts:
                citations = ''.join(f'<span class="citation">{c}</span>' for c in f.supporting_evidence)
                parts.append(f'<li>{f.statement}<div class="citations">{citations}</div></li>')
            parts.append('</ol></section>')

        # Financial Summary
        if self.financial_summary:
            parts.append('<section class="summary-section"><h3>Financial Summary</h3><ul class="fact-list">')
            for item in self.financial_summary:
                citations = ''.join(f'<span class="citation">{c}</span>' for c in item.supporting_evidence)
                parts.append(f'<li><strong>{item.amount}</strong> — {item.description}<div class="citations">{citations}</div></li>')
            parts.append('</ul></section>')

        # Claims
        if self.claims:
            parts.append('<section class="summary-section"><h3>Claims</h3><ol class="claim-list">')
            for c in self.claims:
                citations = ''.join(f'<span class="citation">{ev}</span>' for ev in c.supporting_evidence)
                parts.append(f'<li>{c.description}<div class="citations">{citations}</div></li>')
            parts.append('</ol></section>')

        # Uncertainties
        if self.uncertainties:
            parts.append('<section class="summary-section"><h3>Uncertainties</h3><ul class="uncertainty-list">')
            for u in self.uncertainties:
                parts.append(f'<li>{u}</li>')
            parts.append('</ul></section>')

        parts.append('</div>')
        return '\n'.join(parts)

    def to_markdown(self) -> str:
        """Render a readable Markdown summary for copy/paste."""
        lines = ['# Case Fact Summary\n']

        if self.document_summary:
            lines.append(f'**Document Overview:** {self.document_summary}')
            lines.append('')

        if self.parties:
            lines.append('## Parties')
            for p in self.parties:
                role = f' ({p.role})' if p.role else ''
                lines.append(f'- **{p.name}**{role}')
            lines.append('')

        if self.dates:
            lines.append('## Key Dates')
            for d in self.dates:
                lines.append(f'- **{d.date}** — {d.event}')
            lines.append('')

        if self.key_facts:
            lines.append('## Key Facts')
            for i, f in enumerate(self.key_facts, 1):
                cites = ', '.join(f.supporting_evidence)
                lines.append(f'{i}. {f.statement}  `[{cites}]`')
            lines.append('')

        if self.financial_summary:
            lines.append('## Financial Summary')
            for i, item in enumerate(self.financial_summary, 1):
                cites = ', '.join(item.supporting_evidence)
                lines.append(f'{i}. **{item.amount}** — {item.description}  `[{cites}]`')
            lines.append('')

        if self.claims:
            lines.append('## Claims')
            for i, c in enumerate(self.claims, 1):
                cites = ', '.join(c.supporting_evidence)
                lines.append(f'{i}. {c.description}  `[{cites}]`')
            lines.append('')

        if self.uncertainties:
            lines.append('## Uncertainties')
            for u in self.uncertainties:
                lines.append(f'- {u}')
            lines.append('')

        return '\n'.join(lines)
